//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcion
    {
        public Funcion()
        {
            this.Reservacion = new HashSet<Reservacion>();
        }
    
        public int idfuncion { get; set; }
        public string hora { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idsala { get; set; }
        public Nullable<bool> estado { get; set; }
        public Nullable<int> idpelicula { get; set; }
    
        public virtual Pelicula Pelicula { get; set; }
        public virtual Sala Sala { get; set; }
        public virtual ICollection<Reservacion> Reservacion { get; set; }
    }
}
