//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id { get; set; }
        public string codbutaca { get; set; }
        public Nullable<int> idfuncion { get; set; }
    
        public virtual Funcion Funcion { get; set; }
    }
}
